name: Run GitHub Email Scraper

on:
  schedule:
    - cron: '0 */6 * * *' # Running every 6 hours
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Setup Google Sheets API Credentials
        run: |
          echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS_JSON }}" > credentials.json

      - name: Run Python Script
        env:
          MY_GITHUB_API_KEYS: ${{ secrets.MY_GITHUB_API_KEYS }}  # GitHub API keys for scraping
        run: |
          python github_email_scraper.py
